name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "primeira acao"
        run: echo "primeira acao"
      - name: "segunda acao"
        run: |
          echo "inicializando segunda acao"
          echo "finalizando segunda acao"
      - name: "acao python"
        run: |
          variavel = "Ola python"
          print(variavel)
        shell: python
